### ISSUE TITLE
Add syntax highlighting 

### ISSUE THREAD

**Issue by ChronicSomogyiRebound** [Vinatorul/vinatorul.github.io#16]
![image](https://cloud.githubusercontent.com/assets/15072218/19921432/eedec14e-a0ee-11e6-84d2-2e5ed65875da.png)

**Comment by ChronicSomogyiRebound** [comment]
```cpp   
int LCM(const int x, const int y) {
    return x\GCD(x, y)*y;
}
``` 
Будет работать?

**Comment by Vinatorul** [comment]
Там похоже, что просто стили поломались, т.к. если посмотреть на результирующую страничку - подсветка там есть
