### ISSUE TITLE
Design issues

### ISSUE THREAD

**Issue by mvlabat** [Vinatorul/vinatorul.github.io#26]
## Bugs
- [x] `Read more` link and the line next to it are not on the same height
- [ ] Footer content is shifted to the right relatively to the border line

## Things to improve
- [x] It is better to leave recent posts links without background
- [ ] Increase paddings. Would be good to have them for `posted by` and also between footer border line and its content
- [ ] Try to separate `posted by` and date. Make `float: right` for date maybe
- [ ] I think paging buttons should repeat border radius of sidebar blocks
- [ ] Center pagination

**Comment by Vinatorul** [comment]
Not relevant due to redesign
